Update location format in log messages (#48)
* Update location format in log messages

Update location format to:
```
error: My Message
  File: /absolute/path/to/MyFile.fsh
  Line: 12 - 14
```
Based on team discussion.

* Fix tests missing \D at the end of the log message matcher